version: '3.9'

services:
  speakup-service:
    image: speakup-service:latest
    ports:
      - "80:8080"
    environment:
      - SPRING_DATASOURCE_URL="${SPRING_DATASOURCE_URL}"
      - SPRING_DATASOURCE_USERNAME="${SPRING_DATASOURCE_USERNAME}"
      - SPRING_DATASOURCE_PASSWORD="${SPRING_DATASOURCE_PASSWORD}"
    depends_on:
      - video-transform-service

  video-transform-service:
    image: sarriaq/video-transform-service:latest