version: '1.0'
services:
  dev-database-postgres:
    build: .
    image: "dev-postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always